import { defineConfig } from 'tsdown';

export default defineConfig((options) => ({
  dts: true,
  clean: !options.watch,
  target: ['es2020'],
  format: ['esm', 'cjs'],
  platform: 'browser',
  entry: {
    index: 'src/index.ts',
    events: 'src/events.ts',
    i18n: 'src/i18n.ts',
    'image-service': 'src/image-service.ts',
    styles: 'src/styles.ts',
    thumbnail: 'src/thumbnail.ts',
    'annotation-targets': 'src/annotation-targets.ts',
    'content-state': 'src/content-state.ts',
    fetch: 'src/fetch.ts',
    'painting-annotations': 'src/painting-annotations.ts',
    ranges: 'src/ranges.ts',
    sequences: 'src/sequences.ts',
    'nav-date': 'src/nav-date.ts',
    vault: 'src/vault.ts',
    'vault-4': 'src/vault/vault4.ts',
    'vault-auto': 'src/vault/vault-auto.ts',
    'vault-node': 'src/vault-node.ts',
    'vault-store': 'src/vault-store.ts',
    'vault-actions': 'src/vault-actions.ts',
    'vault-utility': 'src/vault-utility.ts',
    transcriptions: 'src/transcriptions.ts',
    search1: 'src/search1.ts',
    search2: 'src/search2.ts',
    // New helpers can be added here.
  },
  define: { 'import.meta': '{}' },
  minify: true,
  external: [],
  // @todo re-enable.
  // globalName: 'IIIFHelpers',
}));
